apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
  namespace: streaming-iot
spec:
  serviceName: redpanda
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: redpandadata/redpanda:latest
          command:
            - redpanda
            - start
            - --smp=1
            - --memory=512M
            - --overprovisioned
            - --kafka-addr=0.0.0.0:9092
            - --advertise-kafka-addr=redpanda-0.redpanda.streaming-iot.svc.cluster.local:9092
          ports:
            - containerPort: 9092
              name: kafka
            - containerPort: 9644
              name: admin
          readinessProbe:
            exec:
              command:
                - rpk
                - cluster
                - health
                - --api-urls
                - localhost:9644
            initialDelaySeconds: 5
            periodSeconds: 5
